blank_issues_enabled: false
contact_links:
  - name: ðŸ¤” Having doubts or questions?
    url: https://github.com/memstechtips/UnattendedWinstall/discussions
    about: Create a discussion and get help from other members of the community
  - name: ðŸ“§ Contact me privately by email
    url: mailto:contact@memstechtips.com
    about: Please use only if the issue (for example, a vulnerability) cannot be posted publicly
